import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} th-subpixel-antialiased th-scroll-smooth th-flex th-items-center th-justify-center th-min-h-dvh th-max-w-dvh`}
      >
        {children}
      </body>
    </html>
  );
}
